import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";


export const myFont = localFont({
  src: [
    {
      path: "./fonts/ZalandoSansSemiExpanded-VariableFont_wght.ttf",
      weight: "200",
      style: "normal",
    },
  ],
  variable: "--font-myfont",
});

export const Encode = localFont({
  src: "./fonts/EncodeSans-VariableFont_wdth,wght.ttf",
  variable: "--font-encode",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Encode.variable} ${myFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
